# Generated by Django 3.1 on 2023-05-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20230516_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='folders',
            field=models.ManyToManyField(blank=True, to='post.Folder'),
        ),
    ]
