# Generated by Django 3.1 on 2023-05-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_post_folders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='folders',
        ),
        migrations.AddField(
            model_name='folder',
            name='posts',
            field=models.ManyToManyField(to='post.Post'),
        ),
    ]
