# Generated by Django 3.1 on 2023-05-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20230519_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='posts',
            field=models.ManyToManyField(blank=True, to='post.Post'),
        ),
    ]
