# Generated by Django 3.1 on 2023-05-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20230519_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='is_public',
        ),
        migrations.AddField(
            model_name='folder',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('selected', 'Selected')], default='private', max_length=10),
        ),
    ]
