# Generated by Django 3.1 on 2023-05-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_folder_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('selected', 'Selected')], default='private', max_length=10, null=True),
        ),
    ]
