# Generated by Django 4.1.4 on 2023-06-06 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_movie_already_seen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directs', '0003_auto_20220213_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=50)),
                ('on', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.movie')),
                ('reciepient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciepient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.series')),
            ],
        ),
    ]
