# Generated by Django 4.1.4 on 2023-05-28 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_alter_playlist_access_alter_playlist_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authy', '0009_auto_20230516_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=50)),
                ('caption', models.CharField(max_length=50)),
                ('live_till', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.movie')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
