# Generated by Django 4.1.4 on 2023-05-23 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('overview', models.TextField()),
                ('poster', models.URLField()),
                ('release_date', models.CharField(max_length=50)),
                ('revenue', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('tagline', models.CharField(max_length=50)),
                ('adult', models.BooleanField()),
                ('popularity', models.IntegerField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('air_date', models.CharField(max_length=50)),
                ('episode_count', models.IntegerField()),
                ('overview', models.TextField()),
                ('poster', models.URLField()),
                ('season_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('overview', models.TextField()),
                ('poster', models.URLField()),
                ('release_date', models.CharField(max_length=50)),
                ('creator_name', models.CharField(max_length=50)),
                ('logo', models.URLField()),
                ('first_air_date', models.CharField(max_length=50)),
                ('in_production', models.BooleanField()),
                ('no_of_episodes', models.IntegerField()),
                ('no_of_seasons', models.IntegerField()),
                ('origin_country', models.CharField(max_length=50)),
                ('tagline', models.CharField(max_length=50)),
                ('adult', models.BooleanField()),
                ('popularity', models.IntegerField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('title', models.CharField(max_length=50)),
                ('access', models.ManyToManyField(related_name='shared_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movies', models.ManyToManyField(to='search.movie')),
                ('saved_by', models.ManyToManyField(related_name='saved', to=settings.AUTH_USER_MODEL)),
                ('series', models.ManyToManyField(to='search.series')),
            ],
        ),
    ]
