# Generated by Django 4.1.4 on 2023-05-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='adult',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='series',
            name='first_air_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='in_production',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='no_of_episodes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='no_of_seasons',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='origin_country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='overview',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='popularity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='poster',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='production_logo',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='production_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='release_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='tagline',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='vote_average',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='vote_count',
            field=models.IntegerField(null=True),
        ),
    ]
