# Generated by Django 4.1.4 on 2023-05-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_movie_language_alter_movie_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='production_logo',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
