# Generated by Django 4.1.4 on 2023-05-25 10:48

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0005_movie_production_logo_movie_production_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='access',
            field=models.ManyToManyField(null=True, related_name='shared_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='key',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='movies',
            field=models.ManyToManyField(null=True, to='search.movie'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='saved_by',
            field=models.ManyToManyField(null=True, related_name='saved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='series',
            field=models.ManyToManyField(null=True, to='search.series'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
