# Generated by Django 4.1.4 on 2023-05-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_alter_playlist_access_alter_playlist_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='lit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='shit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playlist',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='lit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='shit',
            field=models.IntegerField(default=0),
        ),
    ]
