# Generated by Django 4.1.4 on 2023-06-01 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0007_movie_lit_movie_shit_playlist_likes_series_lit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='likes',
        ),
        migrations.AddField(
            model_name='playlist',
            name='liked_by',
            field=models.ManyToManyField(null=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
