# Generated by Django 4.1.4 on 2023-06-01 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0008_remove_playlist_likes_playlist_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='already_seen',
            field=models.ManyToManyField(related_name='seen', to=settings.AUTH_USER_MODEL),
        ),
    ]
